baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tufts ME-30"
theme = "book"
enableGitInfo = true
[params]
  BookSection = '*'
  BookRepo = 'https://github.com/pingswept/me30-website'
  BookEditPath = 'edit/master'
[markup.goldmark.renderer]
  unsafe= true
