baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tufts ME-30"
theme = "book"
enableGitInfo = true
staticDir = ["/"]
[params]
  BookSection = '*'
  BookRepo = 'https://github.com/pingswept/me30-website'
  BookEditPath = 'edit/master/content'
[markup.goldmark.renderer]
  unsafe= true
