name: Run Hugo via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: 'root@23.239.11.134:22'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: false
          command: ls -lah
